services:
  - type: web
    name: koder-backend-test
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGOOSE_URL
        sync: false
      - key: JWT_SECRET
        sync: false